# Generated by Django 4.0.5 on 2022-06-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupant_name', models.CharField(max_length=100)),
                ('Occupant_email', models.EmailField(max_length=254)),
                ('Occupant_occupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.IntegerField(default=1)),
                ('Amount_paid', models.CharField(max_length=20)),
                ('Num_of_nights', models.IntegerField(default=1)),
                ('Start_date', models.DateField()),
                ('Customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
