# Generated by Django 4.0.5 on 2022-06-16 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='End_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
