# Generated by Django 4.0.5 on 2022-06-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_record_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
