# Generated by Django 4.0.5 on 2022-06-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_record_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Customer',
            field=models.ForeignKey(default='Ogunleye John', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
