# Generated by Django 4.0.5 on 2022-06-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_record_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Num_of_nights',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='Room_number',
            field=models.IntegerField(),
        ),
    ]
