# Generated by Django 4.0.5 on 2022-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_record_customer_alter_record_num_of_nights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='End_date',
            field=models.DateField(),
        ),
    ]
